### ISSUE TITLE
Exception raised if Cura is closed with tweak at Z plugin enabled

### ISSUE THREAD

**Issue by kakaroto** [alephobjects/Cura#115]
If we add the tweakAtZ plugin, then close Cura, an exception is printed in the terminal :
```
Traceback (most recent call last):
  File "/home/kakaroto/coding/alephobjects/Cura/Cura/gui/pluginPanel.py", line 150, in OnSettingChange
    if type(panel.paramCtrls[k].GetValue()) == bool:
  File "/usr/lib64/python2.7/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14606, in __getattr__
    raise PyDeadObjectError(self.attrStr % self._name)
wx._core.PyDeadObjectError: The C++ part of the TextCtrl object has been deleted, attribute access no longer allowed.
```

**Comment by reprapperMC** [comment]
This issue has now been duplicated at https://code.alephobjects.com/T35. Please move any future discussion there as issues will shortly no longer be tracked on this Github repo.
