### ISSUE TITLE
Cura -r option doesn't work

### ISSUE THREAD

**Issue by kakaroto** [alephobjects/Cura#62]
Looking at the code,I saw that the -r option calls printWindow.startPrintInterface which doesn't exist, so calling cura with the -r option will just show an error :
```
kakaroto@kakaroto:~/coding/alephobjects/Cura$ ./cura -r tst.gcode 
load preferences from /home/kakaroto/.cura/?/preferences.ini
Traceback (most recent call last):
  File "/home/kakaroto/coding/alephobjects/Cura/cura.py", line 34, in <module>
    cura.main()
  File "/home/kakaroto/coding/alephobjects/Cura/Cura/cura.py", line 53, in main
    printWindow.startPrintInterface(options.printfile)
AttributeError: 'module' object has no attribute 'startPrintInterface'
```

**Comment by kakaroto** [comment]
I would suggest removing the -r option since it involves a lot of work to add such a feature which I don't think is even worth it, especially when it comes to selecting the connection, what if the user specifies an stl instead of a gcode and doesn't have a machine profile setup, etc.. 
I don't think Cura is really meant to be used that way, without a main window.. so what do you think? remove the option? or implement it ?

**Comment by kakaroto** [comment]
I've removed the option. Closing
