### ISSUE TITLE
57600b causing error

### ISSUE THREAD

**Issue by reprapperMC** [alephobjects/Cura#76]
Commit 57600b4bc49 is causing an error when loading a gcode file.

Traceback (most recent call last):
  File "/usr/share/cura/Cura/gui/mainWindow.py", line 380, in OnModelMRU
    self.scene.loadFiles(filelist)
  File "/usr/share/cura/Cura/gui/sceneView.py", line 158, in loadFiles
    self.loadGCodeFile(gcodeFilename)
  File "/usr/share/cura/Cura/gui/sceneView.py", line 133, in loadGCodeFile
    self.viewSelection.setValue(4)
  File "/usr/share/cura/Cura/gui/util/openglGui.py", line 637, in setValue
    self._imageID = self._imageIDs[self._selection+1]
IndexError: list index out of range

**Comment by Jnesselr** [comment]
Hmm, I wonder how that got in there. I checked the offset code and it was working. I removed the offending code, recompiled, and uploaded a fix to the master branch.
