### ISSUE TITLE
Python error on loading Cura

### ISSUE THREAD

**Issue by kakaroto** [alephobjects/Cura#88]
I've only had this error once in my terminal :
```
Traceback (most recent call last):
  File "/home/kakaroto/coding/alephobjects/Cura/Cura/gui/util/openglGui.py", line 187, in _OnGuiMouseDown
    self.OnMouseDown(e)
  File "/home/kakaroto/coding/alephobjects/Cura/Cura/gui/sceneView.py", line 787, in OnMouseDown
    self._mouseClick3DPos = self._mouse3Dpos
AttributeError: 'SceneView' object has no attribute '_mouse3Dpos'
```

Looking at the code, it looks like the mouse3Dpos is used in the OnMouseDown callback but is set in the OnPaint callback, so this seems to indicate that it received a mouse down event before the first paint event.. I'm not sure how it could happen, but we'd better fix it.

**Comment by kakaroto** [comment]
Fixed
