### ISSUE TITLE
python Exception in master

### ISSUE THREAD

**Issue by kakaroto** [alephobjects/Cura#91]
While testing the new simple settings code, I was doing a lot of changes to settings to see if the right options get used, and while doing that, I saw a few times the following errors :

```
Exception in thread Thread-60:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/kakaroto/coding/alephobjects/Cura/Cura/util/sliceEngine.py", line 135, in <lambda>
    self._gcodeLoadThread = threading.Thread(target=lambda : self._gcodeInterpreter.load(self._gcodeData.clone()))
  File "/home/kakaroto/coding/alephobjects/Cura/Cura/util/gcodeInterpreter.py", line 56, in load
    self._load(data)
  File "/home/kakaroto/coding/alephobjects/Cura/Cura/util/gcodeInterpreter.py", line 123, in _load
    gcodeFile.close()
AttributeError: 'BigDataStorage' object has no attribute 'close'
```

I'm unable to reproduce it for now so I'm not sure what causes it, but it should be easy to figure out once I look at the code.

note: the BigDataStorage stuff was added after 14.09 so this only affects the master branch which has upstream commits merged into it.

**Comment by kakaroto** [comment]
Only seems to happen if we cancel the processing of the gcode while a new gcode has been sliced. Pretty hard to reproduce, but it could happen and doesn't only affect BigDataStorage.
Fixed now. closing.
