### ISSUE TITLE
slicing Exception unhandled on invalid profile settings

### ISSUE THREAD

**Issue by kakaroto** [alephobjects/Cura#95]
If we enter an invalid value for a profile setting by mistake or while trying to enter a different value, then the field becomes red indicating it's an invalid value, but the slicing action is still attempted resulting in an exception being printed in stdout, for example :

Enter `.` for filament diameter :
```
Exception in thread Thread-42:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/kakaroto/coding/alephobjects/Cura/Cura/util/sliceEngine.py", line 419, in _runEngine
    self._result.addReplaceTag('#F_WGHT#', math.floor(self._result.getFilamentWeight(0) * 1000.0))
  File "/home/kakaroto/coding/alephobjects/Cura/Cura/util/sliceEngine.py", line 74, in getFilamentWeight
    radius = float(profile.getProfileSetting('filament_diameter')) / 2
ValueError: could not convert string to float: .
```
Enter `3.-` instead of  `3.0` for filament diameter :
```
Exception in thread Thread-48:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/kakaroto/coding/alephobjects/Cura/Cura/util/sliceEngine.py", line 306, in _runEngine
    self._callback(-1.0)
  File "/home/kakaroto/coding/alephobjects/Cura/Cura/gui/sceneView.py", line 675, in _updateEngineProgress
    amount = result.getFilamentAmount(e)
  File "/home/kakaroto/coding/alephobjects/Cura/Cura/util/sliceEngine.py", line 101, in getFilamentAmount
    return _('%0.2f meter %0.0f gram') % (float(self._filamentMM[e]) / 1000.0, self.getFilamentWeight(e) * 1000.0)
  File "/home/kakaroto/coding/alephobjects/Cura/Cura/util/sliceEngine.py", line 74, in getFilamentWeight
    radius = float(profile.getProfileSetting('filament_diameter')) / 2
ValueError: invalid literal for float(): 3.-
```

Enter `0` for layer height (for example when replacing the value with something, you start by typing 0, then the error pops in the terminal before you finish typing the rest of it) :
```
Exception in thread Thread-52:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/kakaroto/coding/alephobjects/Cura/Cura/util/sliceEngine.py", line 319, in _runEngine
    for k, v in self._engineSettings(extruderCount).iteritems():
  File "/home/kakaroto/coding/alephobjects/Cura/Cura/util/sliceEngine.py", line 534, in _engineSettings
    settings['fanFullOnLayerNr'] = (fanFullHeight - settings['initialLayerThickness'] - 1) / settings['layerThickness'] + 1
ZeroDivisionError: integer division or modulo by zero
```

The solution here is to either catch those exceptions and cancel the slicing thread without printing anything to stdout, or simply not to schedule a re-slicing operation if we know that there is an invalid value.

**Comment by kakaroto** [comment]
I think I caught them all, so closing for now. If there's a new exception that pops up, we can reopen.
